name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm --filter vite-plugin-galias test:types
      - run: pnpm --filter vite-plugin-galias build
      - run: pnpm --filter vite-plugin-galias vitest --coverage
      - uses: codecov/codecov-action@v3
