# For security reasons, the workflow in which the autofix.ci action is used must be named "autofix.ci".
name: autofix.ci
on:
  pull_request:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - name: Fix lint issues
        run: pnpm lint:fix
      - uses: autofix-ci/action@8caa572fd27b0019a65e4c695447089c8d3138b9
        with:
          commit-message: 'chore: apply automated fixes'
